### ISSUE TITLE
Gitlab account activation

### ISSUE THREAD

**Issue by bhedana** [BurnerDev/NUC#4]
Gitlab requires account email activation
that email does not appear to be sent

**Comment by ToddFute** [comment]
Ah crappola. During the setup I told it not to set up email because I didn't want to deal with it at the time. I'll figure out how to enable it.

**Comment by ToddFute** [comment]
So the options during the install are:

No configuration:
  Should be chosen to leave the current configuration unchanged.
Internet site:
  Mail is sent and received directly using SMTP.
Internet with smarthost:
  Mail is received directly using SMTP or by running a utility such as fetchmail. outgoing mail is sent using a smarthost.
Satellite system:
  All mail is sent to another machine, called a 'smarthost', for delivery.
Local only:
  The only delivered mail is the mail for local users. There is no network.

I was assuming that choosing SMTP would mean we'd have to run a SMTP host. What do you think?
