### ISSUE TITLE
Apt server sync automation

### ISSUE THREAD

**Issue by bhedana** [BurnerDev/NUC#7]
will the apt server mirror update it's store automatically or does this require manual action?

**Comment by ToddFute** [comment]
I didn't use the "and continue syncing". I wasn't sure if it would normally have an internet connection and what it would do if/when it tried and there was none. As I understand it, it's pretty easy to curl that into place. I'll make it so.

**Comment by ToddFute** [comment]
Oops, that answer was for npm. For apt ...

I've put a crontab entry:

0 2 * * * /usr/bin/apt-mirror >> /var/log/apt-mirror.log

So now at 2am it will do an update. I expect this to be pretty quick with only a day's worth of changes.
